show:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: ha_desktop_widget

hide:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: ha_desktop_widget

toggle:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: ha_desktop_widget

switch_page:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: ha_desktop_widget
    page_id:
      required: true
      selector:
        text:

apply_profile:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: ha_desktop_widget
          multiple: true
    profile:
      required: true
      selector:
        text:

unassign_profile:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: ha_desktop_widget
          multiple: true

capture_profile:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: ha_desktop_widget
    name:
      required: true
      selector:
        text:

save_profile:
  fields:
    name:
      required: true
      selector:
        text:
    document:
      required: true
      selector:
        object:

delete_profile:
  fields:
    profile:
      required: true
      selector:
        text:
